/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    kotlin("jvm") version "1.7.20"
    `maven-publish`
}

repositories {
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.google.guava:guava:31.0.1-jre")
}

group = "mike"
version = "1.0"
description = "bedrockformation"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.jar {
    manifest {
        attributes (
            "Main-Class" to "com.mike.Main"
                )
    }
}
